version: "3.8"

services:
  mysql-db:
    container_name: blue_harvest_db
    image: richardleeabraham/blue_harvest_db:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306
    ports:
      - 3306:3306
    restart: always

  app:
    image: blue_harvest_app:latest
    depends_on:
      - "mysql-db"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"