spring:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/blueharvest
    username: root
    password: blueharvest

server:
  port: 8080
